version: '3.8'

services:
  studentapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver-container
    environment:
      - "ConnectionStrings:DefaultConnection=Server=sqlserver-container;Database=StudentDB;User Id=sa;Password=YourStrongPassword;TrustServerCertificate=True"

  sqlserver-container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Shruti_7877"